### ISSUE TITLE
Links in an imported note from a group library does not work as expected

### ISSUE THREAD

**Issue by sierxue** [mgmeyers/obsidian-zotero-integration#207]
When I use `import notes` command to import a note of an item in a group libary, the link does not recognize the group library. 

For example, the correct "Go to annotation" link should be `zotero://open-pdf/groups/2209124/items/SDF2QMJ7?page=3&annotation=DSNN4MDK`, but in the imported note, the link is `zotero://open-pdf/library/items/SDF2QMJ7?page=2488&annotation=DSNN4MDK`; the correct item link should be `zotero://select/groups/2209124/items/LCJNYRT4`, but in the imported note, the link is `zotero://select/library/items/LCJNYRT4`.

A solution should be replacing `library` with `groups/2209124` in both links.

How can I fix it by changing the settings of the plugin?

Thanks in advance!

**Comment by dawasari** [comment]
I'm experiencing the same issue

**Comment by jeron1** [comment]
My (local) Library does not have the issue, but group libraries do have the problem. Links in imported notes in obsidian have the following behavior, depending on whether or not the PDF is in My (local) Library or one of my group libraries:

Works well: My (local) Library:
Opens to pdf page with highlight annotation:
`zotero://open-pdf/library/items/LUS8NCWP?page=2`
Opens to appropriate line item in my library:
`zotero://select/library/items/7KE5UD2D`

Problem: with my group libraries:
Expected behavior:
open to pdf page with highlight annotation:
zotero://open-pdf/library/items/PV42WNDG?page=1
Actual result:
just launches zotero (or brings it to the foreground) to last viewed position
Partial remedy (based on **[sierxue](https://github.com/sierxue)** comment):
if I change in the link `library` to `groups/4698737` it works, i.e., the following will open to pdf page with highlight annotation:
`zotero://open-pdf/groups/4698737/items/PV42WNDG?page=1`

Expected behavior:
open to appropriate line item in group library
`zotero://select/library/items/7G2FBYEB`
Actual result:
just launches zotero (or brings it to the foreground) to last viewed position
Partial remedy (based on **[sierxue](https://github.com/sierxue)** comment):
f I change in the link `library` to `groups/4698737` it works, i.e., the following will open to appropriate line item in my library:
`zotero://select/groups/4698737/items/7G2FBYEB`

I have several group libraries, and each has its own number, so if I want to link to a PDF in a different group library I have to find out the group library number.  Editing links would be time consuming, so for now, if I am highlighting PDFs (with the intention of importing into obsidian), it is only efficient for me to do so on my PC with PDFs in My (Local) Library and not on my ipad with PDFs in a group library.

Using obsidian v1.2.8 (installer v.1.2.7)
zotero 6.0.26
zotero integration 2.3.9
linux kde neon 5.27

**Comment by mgmeyers** [comment]
This should be fixed now. Update and let me know if you encounter any issues.

**Comment by jeron1** [comment]
Thank you for working on this. Based on what’s in my obsidian template (parts of which I may need to update), links now have the following outcomes:
group library (cloud) - links to items now work, but links to highlights still don’t
My Library (non-cloud) – links to items no longer work, but links to highlights still do

I am currently running Zotero Integration v2.3.11, Obsidian v1.3.5, Zotero 6.0.26, KDE neon 5.27.6 (ubuntu 22.04).

More specifically:
group library
links to item now work (go to item in zotero)
links to highlighted pdf text still don’t work (only cause zotero to open, but don’t open pdf or go to item item)

My Library
links to item no longer work (possibly broken by recent update, link only causes zotero to open, but not  go to item)
links to highlighted pdf text still work

My template in obsidian was cobbled together over time, and it may need changes (hopefully reference below to “`[local]`” is not confusing—it’s what was in my template, but ideally refers to links to items in My Library (non-cloud) and group libraries (cloud)).

**_Looking at my template_**:
**Link to item** - from my obsidian template:
`[local]({{desktopURI}})`


good for group library:
creates note with following for item in group library (link works):
`[local](zotero://select/groups/4698737/items/XYU2G6ZR)`

no longer good for My Library:
creates note with for item in My Library (link doesn’t work):
`[local](zotero://select/users/6597395/items/NHTRMLEZ)`
previously, working links for My Library, would look like this:
`[local](zotero://select/library/items/NZ9UG24K)`


**Link to highlights** - from my obsidian template:
`[Page {{annot.page}}](zotero://open-pdf/library/items/{{annot.attachment.itemKey}}?page={{annot.page}})`

still not working for group library:
creates note with the following for link to highlight annotation (link doesn’t work):
`[Page 1](zotero://open-pdf/library/items/NHMQFXYI?page=1)`

still is working for My Library:
creates note with the following link which opens pdf to highlight in zotero
`[Page 1](zotero://open-pdf/library/items/J2I5RFBZ?page=1)`


If helpful, the longer bit of code from my template for annotations is below:

```
### Annotations:
{% persist "annotations" %}
{% set annots = annotations | filterby("date", "dateafter", lastImportDate) -%}
{% if annots.length > 0 %}
Imported on {{importDate | format("YYYY-MM-DD h:mm a")}}

{% for color, annots in annots | groupby("color") -%}
##### {{colorValueToName(color)}}

{% for annot in annots -%}
> [!quote{% if annot.color %}|{{annot.color}}{% endif %}] {{calloutHeader(annot.type)}}
{%- if annot.annotatedText %}
> {{annot.annotatedText | nl2br}}
{%- endif -%}
{%- if annot.imageRelativePath %}
> ![[{{annot.imageRelativePath}}]]
{%- endif %}
{%- if annot.ocrText %}
> {{annot.ocrText}}
{%- endif %}
{%- if annot.comment %}
>
>> {{annot.comment | nl2br}}
{%- endif %}
>
> [Page {{annot.page}}](zotero://open-pdf/library/items/{{annot.attachment.itemKey}}?page={{annot.page}}) 

{% endfor -%}
{% endfor -%}
{% endif %}
{% endpersist %}
```

**Comment by mgmeyers** [comment]
Thanks @jeron1 

I've fixed the issues with `desktopURI`.

Regarding linking to annotations, I've added a `desktopURI` to annotations that will open to the correct spot, so you can change your template from this:

```
> [Page {{annot.page}}](zotero://open-pdf/library/items/{{annot.attachment.itemKey}}?page={{annot.page}}) 
```

to this:

```
> [Page {{annot.page}}]({{annot.desktopURI}}) 
```

Let me know if you run into any trouble with this

**Comment by jeron1** [comment]
Outstanding! Thank you @mgmeyers This is very helpful to productivity. Putting to immediate use (despite holiday tomorrow).
